import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import Footer from './components/footer'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title> Project List </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navcont}>
<Link className={styles.nav} 
href="/page/about">About</Link>
<Link className={styles.nav} href="/components/main"> Projects </Link>
</div>
      <div className={styles.main}>
      <h1>
                Hello! I am Nicole. A <div className={styles.wrapper}>
        <div className={styles.btn}>
            <div className={styles.default}>Web Developer</div>
            <div className={styles.hover}> Designer </div>
        </div>
      </div>
         who loves to build things!
            </h1>

       </div>
<Footer/ >
      
    </div>
  )
}
